MyMVC/Controllers/Lession1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyMVC.Models;

namespace MyMVC.Controllers
{
    public class Lession1Controller : Controller
    {
        // GET: Lession1
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index1A()
        {
            return View("IndexHello");
            //在View()裡面強制寫上檢視畫面的檔名
        }

        public ActionResult Index1B()
        {
            return View("~/Views/Lession1/IndexHello.cshtml");
            //在View()裡面強制寫上檢視畫面的完整路徑與檔名
        }

        public String Index1C()
        {
            return "這是Inex1C  <H3>回傳一個字串</H3>";
            //回傳一個字串
        }

        public ActionResult Index1D()
        {
            //回傳一個字串,使用text/palin，不會解讀HTML Tag
            //return Content("這是Inex1D  <H3>使用Content回傳一個Content字串</H3>", "text/palin", System.Text.Encoding.UTF8);
            //回傳一個字串,使用text/html，會解讀HTML Tag
            return Content("這是Inex1D  <H3>使用Content回傳一個Content字串</H3>", "text/html", System.Text.Encoding.UTF8);

        }

        public ActionResult Index1E()
        {
            return Redirect("https://www.hohoho.com.tw");
            //回傳轉址
        }

        //protected override void HandleUnknownAction(string actionName)
        //{
        //    Response.Redirect("https://www.pchome.com.tw/");
        //    //base.HandleUnknownAction(actionName);
        //    //找不到Action時，會進入此方法
        //}

        public ActionResult Index3()
        {
            //ViewData、ViewBag及TempData都是存在Session,變數名稱不能相同
            //ViewBag是ViewData的動態封裝器，兩者儲存內容是共用
            //ViewData["A"] = ViewBag.A
            ViewData["A"] = "(1).字串A 我是ViewData[]";
            ViewBag.B = "(2).字串B ViewBag";
            TempData["C"] = "(3).字串C TempData[]";
            ViewBag.Name = "Peter Bryan";
            return View();
        }

        public ActionResult Index4()
        {
            //強類型View part1
            //ViewBag指定型別
            var albums = new List<Models.Album>();
            for (int i = 0; i < 10; i++)
            {
                albums.Add(new Models.Album { Title = "Product " + i });
            }
            ViewBag.Albums = albums;
            return View();
        }
        public ActionResult Index5()
        {
            //強類型View part2
            //使用ViewData的Model屬性，可以用來在View中取得指定的模型對象
            //ViewData中只能包含一個模型對象 --> return View(albums);
            var albums = new List<Models.Album>();
            for (int i = 0; i < 10; i++)
            {
                albums.Add(new Models.Album { Title = "Album " + i });
            }

            //使用ViewBag再傳遞另一個模型
            var artists = new List<Models.Artist>();
            for (int i = 0; i < 10; i++)
            {
                artists.Add(new Models.Artist { Name = "John'number " + i });
            }
            ViewBag.Artists = artists;

            return View(albums);
        }

        public ActionResult Index6()
        {
            ViewBag.Msg = "<script>alert('無編碼代碼表達式!');</script>";
            //Razor語法
            return View();
        }

        public ActionResult Index7()
        {
            //布局 SiteLayout.cshtml
            return View();
        }

        public ActionResult Index71()
        {
            //布局SiteLayout.cshtml View沒有footer的情況
            return View();
        }

        public ActionResult Index72()
        {
            //布局 SiteLayout.cshtml 使用Partial View 
            ViewBag.Message = "這是載入Index72 部份視圖的ViewBag.Message文字內容!!!";
            return View();
        }

        List<BankCode> listBank = new List<BankCode> {
                new BankCode() { BankId=1001, BankName="中國信托銀行", BankNo="810" }
               ,new BankCode() { BankId=1002, BankName="台新銀行", BankNo="820" }
               ,new BankCode() { BankId=1003, BankName="花旗銀行", BankNo="830" }
               ,new BankCode() { BankId=1004, BankName="聯邦銀行", BankNo="840" }
               ,new BankCode() { BankId=1005, BankName="永豐銀行", BankNo="850" }
               ,new BankCode() { BankId=1006, BankName="土地銀行", BankNo="860" }
               ,new BankCode() { BankId=1007, BankName="中國商業銀行", BankNo="870" }
            };

        public ActionResult IndexBank1()
        {
            List<BankCode> list = null;
            if (Session["Bank"] == null)
                Session["Bank"] = list = listBank;
            else
                list = Session["Bank"] as List<BankCode>;

            Session["Bank"] = list = list.Count == 0  ? listBank : list;//若是都沒資料，就重新給
            return View(list);
        }

        public ActionResult Delete(int id = 1003)
        {
            List<BankCode> list = null;
            if (Session["Bank"] == null)
                Session["Bank"] = listBank;
            else
                list = Session["Bank"] as List<BankCode>;

            var item = from b in list
                       where b.BankId.Equals(id)
                       select b;
            list.Remove(item.FirstOrDefault());
            Session["Bank"] = list;

            return RedirectToAction("IndexBank1");
            //return View("IndexBank1");
        }

        public ActionResult Index8()
        {
            ViewBag.Message = "Index8";
            return View();
        }

        public ActionResult Index81()
        {
            ViewBag.QMsg = Request["q"];
            return View();
        }

        public ActionResult Index9()
        {
            //Html.BeginForm
            //Html.ValidationSummary
            ModelState.AddModelError("", "這是模型級別的錯誤!");
            //增加一個Title屬性的錯誤
            ModelState.AddModelError("Title", "這是與Title屬性相關聯的錯誤 !!!");
            //增加一個Name屬性的錯誤
            ModelState.AddModelError("Name", "Name姓名不可空白 !!!");
            //Html.TextBox("Price")自動繫結ViewBag.Price
            ViewBag.Price = 95.7;
            ViewBag.Album = new Album { Price = 23 };
            //SelectListItem item = new SelectListItem() { Text= "Apple", Value="apple" };
            IList<SelectListItem> list = new List<SelectListItem>() {
                new SelectListItem() { Text= "Apple", Value="apple"}
               ,new SelectListItem() { Text= "Orange", Value="orange"}
               ,new SelectListItem() { Text= "香蕉", Value="banana"}
             };
            
            ViewBag.Genres = new SelectList(list, "Value", "Text");

            var artist = new Artist { Name = "習大大的強型別", ArtistId=2134 };
            return View(artist);
        }

        [ChildActionOnly]
        public ActionResult Index91()
        {
            //設定ChildActionOnly屬性，避免通過URL來調用Index91操作，
            //限制只能通過Action或RenderAction方法來調用子操作，像是顯示網站菜單
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult Index92(BankCode banks)
        {
            //PartialView 接收一個物件
            return PartialView(banks);
        }

        [ChildActionOnly]
        [System.Web.Mvc.ActionName("AddBank")]//設定ActionName原本Index93的 Action將無法使用
        public ActionResult Index93()
        {
            //設定ChildActionOnly屬性，避免通過URL來調用Index93操作，
            //限制只能通過Action或RenderAction方法來調用子操作，像是顯示網站菜單
            //設定ActionName別名來調用action
            return PartialView();
        }    
    
        public ActionResult Index10()
        {
            //驗證和模型狀態
            //模型狀態中存在錯誤，ModelState.IsValid會返回false，下面所有表達式都返回true
            //ModelState.IsValid == false
            //ModelState.IsValidField("Name") == false
            //ModelState["Name"].Errors.Count > 0 
            
            //在模型狀態中查看驗證失敗錯誤訊息
            //var ErrMsg= ModelState["Name"].Errors[0].ErrorMessage;

            if(ModelState.IsValid)
            {
                //驗證成功後要處理的內容
                string Msg="";

            }
            return PartialView();
        }
        
        public ActionResult Index11()
        {
            //Ajax helper Ajax.ActionLink / Ajax.BeginForm
            return View();
        }
        
        public ActionResult Index11a()
        {
            //使用Ajax.ActionLink回傳的內容
            return PartialView();
        }                                 
        public ActionResult Index11b()
        {
            //這是使用Ajax.BeginForm回傳的內容
            ViewBag.SearchTxt = Request["q"];
            return PartialView();
        }

        public ActionResult Index12(string Name)
        {
            //使用jQuery實現自動完成套件
            // var banks= listBank.Where(a => a.BankName.Contains(term)).ToList().Select(a => new {Value = a.BankName});
            var banks= listBank.Where(a => a.BankName.Contains(Name)).Select(a => new {Value = a.BankName});
            //MVC框架不允許使用Json回傳Http Get請求，為了回應Get請求的Json格，需要使用JsonRequestBehavior.AllowGet的設定
            return Json(banks, JsonRequestBehavior.AllowGet);
        }    

        public ActionResult Index13()
        {
            //優化Web頁面性能
            //捆綁(bundling):將多個文件合併成一個文件下載，
            //會在程式啟動時自動配置，配置好的文件會儲存在App_start資料夾中的BundleConfig.cs檔
            //微小(minification):壓縮文件大小
            ViewBag.SearchTxt = Request["q"];
            return PartialView();
        }

        //驗證輸入值
        public System.Web.Mvc.JsonResult CheckUserName(string username)
        {
            //回傳一個布林值
            var result = username == "David";
            return Json(result, System.Web.Mvc.JsonRequestBehavior.AllowGet);
        }


    }
}

MyMVC/Views/Lession1/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>這是Lession1的Index</title>
</head>
<body>
    <h3>這是Lession1的Index!</h3>
    <div> 
    </div>
</body>
</html>

MyMVC/Views/Lession1/Index10.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index10</title>
</head>
<body>
    <h3>這是 Index10 Partial View</h3>
</body>
</html>

MyMVC/Views/Lession1/Index11a.cshtml
@{
    Layout = null;
}


@using (Html.BeginForm("Index81", "Lession1", FormMethod.Post
    , new {target ="_blank", @class = "editForm", data_val=true } ))
{
    <span>查詢條件：</span> 
    <input type="text" name="q" value="" /><br />
    <input type="submit" value="Search" /><br /><br />
    <div>
        <h3>下面的Html輔助方法，生成textarea 會自動 Html編碼</h3>   
        @Html.TextArea("text", "Hello <br /> world !");
    </div>
    
}

MyMVC/Views/Lession1/Index11b.cshtml
<div id="searchresults">
  <h3>這是使用Ajax.BeginForm回傳的內容</h3>
  <P>
   查詢的內容：@ViewBag.SearchTxt</P>
</div>

MyMVC/Views/Lession1/Index13.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index13-使用jQuery實現自動完成套件</title>
</head>
<body>
    <h2>優化Web頁面性能-捆綁(bundling)及 微小(minification)</h2>
    <h3>捆綁(bundling):將多個文件合併成一個文件下載，會在程式啟動時自動配置，
      配置好的文件會儲存在App_start資料夾中的BundleConfig.cs檔, 像是如下</h3>
   <p>
        bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js"));<br>

        bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));<br>

        bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/site.css"));<br>

   </p>
   <h4> 調用捆綁文件可以使用 Include</h4>
      <p> 
       @@Scripts.Render("~/bundles/jquery")</br>
       @@Scripts.Render("~/bundles/jqueryval")</br>
       @@Styles.Render("~/Content/css")</br>
      </p>

    <h3>微小(minification):壓縮文件大小</h3>
    <p>使用jQuery查找帶有 data-autocomplete-source特性的元素</p>
    <input type="text" name="q" data-autocomplete-source="@Url.Action("Index12_QuickSearch","Lession1")"/>

    <script>
      $("input[data-autocomplete-source]").each(function(){
          var target = $(this);
          target.autocomplete({ source:
                target.attr("data-autocomplete-source") });
      });
    </script>
    
</body>
</html>

MyMVC/Views/Lession1/Index4.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index4 - 強類型View part1</title>
</head>
<body>
    <h2> 強類型View part1</h2>

    <h3>ViewBag不指定型別</h3>
    <ul>
        @foreach (dynamic a in ViewBag.Albums) {
            <li>"Title = " @a.Title</li>
        }
    </ul>
    <h3>ViewBag指定型別 IEnumerable<MyMVC.Models.Album> 或 List<MyMVC.Models.Album></h3>
    <ul>
        @*@foreach (MyMVC.Models.Album a in (ViewBag.Albums as List<MyMVC.Models.Album>))
        {
            <li>"Title = " @a.Title</li>
        }*@

        @foreach (MyMVC.Models.Album a in (ViewBag.Albums as IEnumerable<MyMVC.Models.Album>))
        {
            <li>"Title = " @a.Title</li>
        }
    </ul>
    <div> 
    </div>
</body>
</html>

MyMVC/Views/Lession1/Index5.cshtml
@model IEnumerable<MyMVC.Models.Album>
@using MyMVC.Models
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index5</title>
</head>
<body>
    <h3>使用ViewData的Model屬性，在View頁面指定強型別 見第一行宣告 @@model IEnumerab &lt;MyMVC.Models.Album&gt; </h3>
    <b>第二行宣告引用Models型別,使用@@using關鍵字，因此foreach可以直接使用Album類別</b><br />
    <ul>
        @foreach (Album p in Model)
        {
            <li>"Title = " @p.Title</li>
        }
    </ul>

    <h3>使用ViewBag再傳遞另一個模型 MyMVC.Models.Artist</h3>
    @foreach (MyMVC.Models.Artist a in (ViewBag.Artists as IEnumerable<MyMVC.Models.Artist>))
    {
        <li>"Name = " @a.Name</li>
    }

    <h3>經常在View中使用的命名空間，可以在View目錄下的Web.config文件中宣告如下</h3>
       &lt;add namespace="MyMVC.Models"/&gt;
</body>
</html>

MyMVC/Views/Lession1/Index6.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index6</title>
</head>
<body>
    <h3>使用Razor語法</h3>
     <ul>
         <li> <h4>Razor中的核心標記符號是(@@)，稱為"at"  </h4>
         <li> <h4>代碼可能出現有二義性的情況，使用顯性表達式 用小括號()括起來  </h4>
             <div>
                 例如下語法<br />
                 @@{ 
                      string rootNamespace = "MyApp";
                  }<br />
                  &lt;span&gt; @@rootNamespace.Models  &lt;span&gt; <br />
                  這個例子想要輸出的結果是<br />
                  &lt;span&gt; MyApp.Models  &lt;span&gt; <br />
                 此情況反而出現錯誤，Razor會認為@@rootNamespace.Models 是代碼表達式<br />
                 因此可以小括號來使用顯式表達式 如下<br />
                 &lt;span&gt; @@(rootNamespace).Models &lt;/span&gt;
             </div>
            </li>
         <li><h4>使用兩個@@@@ 轉義@@符號 </h4>
             ex:想要顯示 @@Haacke會失敗，使用@@@@符號來轉義
         </li>
         <li><h4>Razor表達式是用HTML自動編碼 </h4>
             例如下語法將不會彈出一個警告對話框，而會呈現編碼的HTML<br />
             @@ {<br />
             string message =  "&lt;script&gt; alert('haacked!');  &lt;/script&gt;" <br />
             }<br />

             @{
                 string message = "<script> alert('haacked!!!');  </script>";
             }<br />
             <span> 編碼的字串 =   @message</span><br />
             <span> 使用@Html.Raw 讓字串不編碼 =  @@Html.Raw(@message)  </span><br />
         </li>

         <li><h4>在javascript中顯示Razor的值，要使用JavaScript字串編碼，可以有效避免XSS功擊</h4>
            ex:<br />
            var message = 'Hello @@Ajax.JavaScriptStringEncode(ViewBag.B)';<br />
            $("#message").html(message).show('slow');<br />
        </li>
         <li><h4>Razor的代碼區塊有兩種</h4>
             <P>
                 單行區塊用@@開頭接識別字<br />
                 ex: @@foreach(var item in Orders)<br />{)<br /> The order is @@item)<br />};<br />
             </P> 
             多行區塊用@@{}，在大括號內的都算 <br />
             ex:<br />
               @@{ <br />
                string s= "one line of code"; <br />
                ViewBag.Title="Another line of code"; <br />
               }<br />
         </li>
         <li><h4>隱式代碼表達式-採用THML編碼</h4>
             &lt;span&gt; Razor: @@model.Message  &lt;/span&gt; <br />
         </li>
         <li>
             <h4>顯式代碼表達式-使用小括號</h4>
             &lt;span&gt; Razor: ISBN@@(isbn) &lt;/span&gt; <br />
         </li>
         <li>
             <h4>無編碼代碼表達式-不採用HTML編碼的值，使用Html.Raw確保不被編碼</h4>
             &lt;span&gt; Razor: @@Html.Raw(model.Message) &lt;/span&gt; <br />
             <div>
                 無編碼=@Html.Raw(@ViewData["Msg"])
             </div>
             <div> 
                 有編碼=@ViewData["Msg"]
             </div>
         </li>
         <li>
             <h4>本文和標記相結合</h4>
             <P>
                 @@foreach(var item in Orders){<br />
                    The order is @@item<br />
                 }<br />
             </P>           
         </li>
         <li>
             <h4>混合代碼和純本文</h4>
             <P>
                 下面展示在一個條件語句塊中顯示純本文<br />
                 第一種: 只將標籤內容寫到回應Response中，標籤本身不寫入<br />
                 @@if(showMesage){ <br />
                 &lt;text&gt; This is plain text &lt;/text&gt; <br />
                 };<br />
                 第二種: 使用特殊語法@@:<br />
                 @@if(showMesage){ <br />
                   @@:This is plain text.<br />
                 }<br />
             </P>
         </li>
         <li>
             <h4>服務器端的注解符號 - 使用@@* ... *@@ 進行多行注解</h4>
             <P>
                 @@*<br />
                   This is a multiline server side comment <br />
                   Server Name = ViewBag.Name <br />
                  *@@ <br />
             </P>
         </li>
         <li>
             <h4>調用泛型方法 - 尖括號會導至Razor轉回標記，因此要用顯示表達式，以小括號括起來</h4>
                @@(Html.SomeMethod&lt;AType&gt; )<br />
         </li>
         <li><h4></h4></li>
         <li><h4></h4></li>
         <li><h4></h4></li>
         <li><h4></h4></li>
         <li><h4></h4></li>
         <li><h4></h4></li>
         <li><h4></h4></li>

         <li><h4></h4></li>
     </ul>
</body>
</html>

MyMVC/Views/Lession1/Index72.cshtml
@{
    Layout = null;
}

<h3>這是index72</h3>
<h3>@ViewBag.Message</h3>

MyMVC/Views/Lession1/Index81.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index81</title>
</head>
<body>
    <span>Index8 查詢條件 = @ViewBag.QMsg</span> 
    <div> 
    </div>
</body>
</html>

MyMVC/Views/Lession1/Index91.cshtml
<br />
<span>================== Index91 Partial View  Start ======================</span>
<h3>這是 Index91 Partial View </h3>
<span>================== Index91 Partial View  End ======================</span>

MyMVC/Views/Lession1/Index92.cshtml
@model MyMVC.Models.BankCode

    <h3>這是 Index92 Partial View - Action要帶一個BankCode Model</h3>
    
    銀行名稱 = @Html.Label("BankName", Model.BankName)<br />
    銀行代碼 = @Html.Label("BankNo", Model.BankNo)<br />

MyMVC/Views/Lession1/IndexBank1.cshtml
@model IEnumerable<BankCode>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IndexBank1</title>
</head>
<body>
     <p>@Html.ActionLink("Create New","Create")</p>
    <table>
        <tr>

            <th>@Html.DisplayNameFor(model => model.BankId) </th>
            <th>@Html.DisplayNameFor(model => model.BankName) </th>
            <th>@Html.DisplayNameFor(model => model.BankNo) </th>
            <th>管理</th>

        </tr>
     @foreach (var item in Model){
      <tr>
          <td>@Html.DisplayFor(modelItem => item.BankId)</td>
          <td>@Html.DisplayFor(modelItem => item.BankName)</td>
          <td>@Html.DisplayFor(modelItem => item.BankNo)</td>
          <td>
              @Html.ActionLink("編輯","Edit", new {id=item.BankId })
              @Html.ActionLink("明細", "Details", new { id = item.BankId })
              @Html.ActionLink("刪除", "Delete", new { id = item.BankId })

          </td>
      </tr>

     }

    </table>

</body>
</html>

MyMVC/Views/Lession1/SiteLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
</head>
<body>
    <h1>這是寫在SiteLayout.cshtml的標題 - @ViewBag.Title</h1>

    <div id="main-content">
        <strong>這是套用layout的View內容------------------start-----------------</strong>
     @RenderBody()  
        <strong>這是套用layout的View內容-------------------end-----------------</strong>
    </div>
    <H3>第一個footer ，直接指定，因同一個layout無法同時載入兩次RenderSection("footer")，此程式已注解</H3>
    @*<footer>@RenderSection("footer")</footer>*@

   <h3>第二個footer，使用if判斷 IsSectionDefined 加入預設值，若無設定會顯示預設footer</h3>
    <footer>
        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer");
        }
        else
        {
            <span>這是Layout預設的footer，當使用Layout的View沒有提供，會顯示這段文字</span>
        }
    </footer>


    <p>
        <h2>使用jQuery的Ajax Load載入一個部份視圖如下</h2>
        <div id="result"></div>
        <script type="text/javascript">
         $(function () {
             $('#result').load('index72');
         });
        </script>
    </p>
</body>
</html>